name: Start pipeline

on:
    push:
        branches: [ develop ]

jobs:
    build:
        name: Build project
        runs-on: windows
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
                node-version: 20

          - name: Install dependencies
            run: npm install

          - name: Run tests
            run: npm test

    deploy:
        name: Deploy to server
        runs-on: windows


        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
                node-version: 20

          - name: Install dependencies
            run: npm install

          - name: Deploy to server
            run: |
              # Здесь добавьте команду для деплоя на ваш сервер
              echo "Deploying to server..."