name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 

    - name: Change directory to project folder
      run: |
        echo "Changing directory to project folder..."
        cd vue-project 

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        cd vue-project 
        ls -la
        npm install

    - name: Build project
      run: |
        cd vue-project
        npm run build
        touch .nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAGES_TOKEN }}
        publish_dir: vue-project/dist
        publish_branch: gh-pages  